
export enum POINTS {
  FIRST_GUESS = 100,
  DRAWING_GOT_GUESSED = 125,
  DRAWING_GOT_GUESSED_ABOVE_FOURTY_SECONDS = 175,
  GUESS = 75,
  GUESS_BELOW_TWENTY_SECONDS = 50
};

export enum GAME_STATE {
  WAITING = "waiting",
  PLAYING = "playing"
};