# fly.toml app configuration file generated for scribbl-websocket on 2023-09-01T14:51:20+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scribbl-websocket"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
